### ISSUE TITLE
SocketTimeout despite staging repository being created

### ISSUE THREAD

**Issue by tomcashman** [marcphilipp/nexus-publish-plugin#48]
Currently receiving the following exception every run despite the staging repository appearing on sonatype.

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':mini2Dx-core:initializeSonatypeStagingRepository'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.io.UncheckedIOException: java.net.SocketTimeoutException: timeout
        at de.marcphilipp.gradle.nexus.internal.NexusClient.createStagingRepository(NexusClient.kt:96)
        at de.marcphilipp.gradle.nexus.InitializeNexusStagingRepository$createStagingRepo$1.apply(InitializeNexusStagingRepository.kt:92)
        at de.marcphilipp.gradle.nexus.InitializeNexusStagingRepository$createStagingRepo$1.apply(InitializeNexusStagingRepository.kt:38)
        at de.marcphilipp.gradle.nexus.InitializeNexusStagingRepository.createStagingRepo$nexus_publish_plugin(InitializeNexusStagingRepository.kt:88)
        at de.marcphilipp.gradle.nexus.InitializeNexusStagingRepository.createStagingRepoAndReplacePublishingRepoUrl(InitializeNexusStagingRepository.kt:83)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:717)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:684)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
        ... 34 more
Caused by: java.net.SocketTimeoutException: timeout
        at de.marcphilipp.gradle.nexus.shadow.okio.Okio$4.newTimeoutException(Okio.java:232)
        at de.marcphilipp.gradle.nexus.shadow.okio.AsyncTimeout.exit(AsyncTimeout.java:285)
        at de.marcphilipp.gradle.nexus.shadow.okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
        at de.marcphilipp.gradle.nexus.shadow.okio.RealBufferedSource.indexOf(RealBufferedSource.java:354)
        at de.marcphilipp.gradle.nexus.shadow.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:226)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at de.marcphilipp.gradle.nexus.internal.NexusClient$1.intercept(NexusClient.kt:53)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at de.marcphilipp.gradle.nexus.shadow.okhttp3.RealCall.execute(RealCall.java:92)
        at de.marcphilipp.gradle.nexus.shadow.retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
        at de.marcphilipp.gradle.nexus.internal.NexusClient.createStagingRepository(NexusClient.kt:90)
        ... 92 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at de.marcphilipp.gradle.nexus.shadow.okio.Okio$2.read(Okio.java:140)
        at de.marcphilipp.gradle.nexus.shadow.okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        ... 116 more
```

**Comment by tomcashman** [comment]
Increasing both connectTimeout and clientTimeout to 15 minutes seems to have resolved the issue. I'm guessing Sonatype is running slow today.

```
nexusPublishing {
  connectTimeout = Duration.ofMinutes(15)
  clientTimeout  = Duration.ofMinutes(15)
  repositories {
    sonatype {
      packageGroup = rootProject.nexusStaging.packageGroup
      stagingProfileId = rootProject.nexusStaging.stagingProfileId
      username = project.getProperty('ossrhUser')
      password = project.getProperty('ossrhPassword')
    }
  }
}
```
